SELECT DEPARTMENT_NAME,MANAGER_ID

FROM DEPARTMENTS

ORDER BY  DEPARTMENT_NAME  ;


SELECT LOCATION_ID , DEPARTMENT_NAME

FROM DEPARTMENTS 

ORDER BY   DEPARTMENT_NAME NULLS FIRST,LOCATION_ID ASC;


SELECT D.LOCATION_ID,D.DEPARTMENT_NAME,COUNT(E.EMPLOYEE_ID)"DEPARTMENTWISE HEADCOUNT"

FROM DEPARTMENTS D 

JOIN EMPLOYEES E

ON D.DEPARTMENT_ID=E.DEPARTMENT_ID

GROUP BY D.LOCATION_ID,D.DEPARTMENT_NAME

ORDER BY D.LOCATION_ID;


 
