SELECT  MATERIAL_SIZE ,  SUM(MATERIAL_QUANTITY),((SUM(MATERIAL_QUANTITY))/12)"AVG_MONTH"

FROM WEBBING  

WHERE material_size IN ('8_MM','10_MM','20_MM')

GROUP BY MATERIAL_SIZE 

ORDER BY MATERIAL_SIZE;



SELECT D.DEPARTMENT_ID ,COUNT(E.EMPLOYEE_ID)"TOTAL_EMPLOYEES",(SUM (E.SALARY))"DEPARTMENT_SALARY ",AVG (E.SALARY)"AVG_SALARY"

FROM  EMPLOYEES E 

JOIN DEPARTMENTS D 

ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 

JOIN JOB_HISTORY J

ON J.DEPARTMENT_ID=D.DEPARTMENT_ID 

JOIN LOCATIONS L

ON D.LOCATION_ID=L.LOCATION_ID

JOIN COUNTRIES C

ON L.COUNTRY_ID=C.COUNTRY_ID

JOIN REGIONS R

ON C.REGION_ID=R.REGION_ID



GROUP BY  D.DEPARTMENT_ID 
--ORDER BY  D.DEPARTMENT_ID 
ORDER BY COUNT (E.EMPLOYEE_ID);