COMMIT
--CREATE STATEMENTS
CREATE TABLE ALL_TEST1 (
TEST_ID INT CONSTRAINT TID_PK PRIMARY KEY,
TEST_STATE VARCHAR2(20) CONSTRAINT TSAT_NN NOT NULL,
TEST_NAME VARCHAR2(10) CONSTRAINT TTNM_NN NOT NULL);

CREATE TABLE TEST_TABLE1 (
TEST_CODE VARCHAR2(20) CONSTRAINT TC_PK PRIMARY KEY,
TEST_ID INT CONSTRAINT TID_REF REFERENCES ALL_TEST1(TEST_ID),
TEST_SUBJ_CODE CHAR(4),
TEST_SUB_MARK INT CONSTRAINT TMRK_CK CHECK (TEST_SUB_MARK < 100));

CREATE TABLE ALL_TEST2 (
EMP_ID INT CONSTRAINT EID_PK PRIMARY KEY,
EMP_NAME VARCHAR2(20) CONSTRAINT ENM_UK NOT NULL UNIQUE ,
EMP_BLOODGRP VARCHAR2(10));

CREATE TABLE EMP_DEPT (
EMP_DEPARTMENT VARCHAR(20) CONSTRAINT EDEPT_PK PRIMARY KEY,
EMP_ID INT CONSTRAINT EMID_REF REFERENCES ALL_TEST2(EMP_ID),
EMP_DESIGNATION VARCHAR2(20) CONSTRAINT EMDES_NN NOT NULL,
EMP_SALARY VARCHAR2(6),
EMP_STATE CHAR(4));

CREATE TABLE EMP_REGION (
EMP_STATE CHAR(4) CONSTRAINT EMST_REF REFERENCES EMP_DEPT(EMP_STATE),
EMP_STATEID VARCHAR(3) CONSTRAINT EMSTID_PK PRIMARY KEY,
EMP_PINCODE VARCHAR(10) CONSTRAINT EPIN_NN NOT NULL);

--ALTER STATEMENTS
ALTER TABLE EMP_DEPT ADD CONSTRAINT EMST_UK_ADDED UNIQUE(EMP_STATE);

RENAME ALL_TEST2 TO EMPLOYEE_ID;

ALTER TABLE TEST_TABLE1 MODIFY TEST_SUBJ_CODE CHAR(10);

ALTER TABLE TEST_TABLE1 ADD (TEST_STUDENT_NAME VARCHAR(15));

ALTER TABLE TEST_TABLE1 ADD CONSTRAINT TSTDTNM_UK_ADDED UNIQUE(TEST_STUDENT_NAME);

ALTER TABLE ALL_TEST1 ADD (TEST_EVENT VARCHAR2(5));

ALTER TABLE ALL_TEST1 RENAME COLUMN TEST_EVENT TO TEST_EVENTS;

ALTER TABLE ALL_TEST1 ADD (TEST_DATE VARCHAR2(5));

ALTER TABLE ALL_TEST1 ADD CONSTRAINT TD_UK_ADDED UNIQUE(TEST_DATE); 

ALTER TABLE ALL_TEST1 ADD CONSTRAINT TD_NN_ADDED CHECK(TEST_DATE IS NOT NULL);COMMIT

ALTER TABLE ALL_TEST1 DROP COLUMN TEST_EVENTS;

ALTER TABLE ALL_TEST1 DROP CONSTRAINT TD_UK_ADDED;

ALTER TABLE ALL_TEST1 DISABLE CONSTRAINT TID_PK CASCADE;--DISABLE PK AND FK WITH CASCADE

ALTER TABLE EMP_DEPT ADD (EMP_NAME VARCHAR2(20));

ALTER TABLE EMPLOYEE_ID RENAME CONSTRAINT SYS_C007470 TO EMBG_UK_ADDED;--RENAMED THE CONSTRAINT SYSNUM TO NAME 

ALTER TABLE EMPLOYEE_ID RENAME CONSTRAINT ENM_UK TO ENM_NN;

ALTER TABLE EMP_DEPT DISABLE CONSTRAINT EMST_UK_ADDED CASCADE ;--DISABLE UNIQUE AND WITH CASCADE

ALTER TABLE EMP_DEPT DROP CONSTRAINT EDEPT_PK;-- DROP A PRIMARY KEY CONSTRAINT 

ALTER TABLE ALL_TEST1 ENABLE CONSTRAINT TID_PK; COMMIT;

ALTER TABLE ALL_TEST1 DROP CONSTRAINT TD_CK;

ALTER TABLE ALL_TEST1 ADD CONSTRAINT TD_NN_ADDED CHECK (TEST_DATES IS NOT NULL);


ALTER TABLE ALL_TEST1 ADD CONSTRAINT TD_CK_ADDED CHECK  (TEST_DATES <= GETDATE());-- NOT CLEARED HAVING DOUBT

ALTER TABLE ALL_TEST1 DROP CONSTRAINT TD_NN_ADDED;

ALTER TABLE ALL_TEST1 DROP COLUMN TEST_DATE ;

ALTER TABLE ALL_TEST1 ADD  TEST_DATES DATE;

TRUNCATE TABLE ALL_TEST1;