CREATE TABLE DEMO_1 (
PATIENT_ID VARCHAR2(15),
PATIENT_NAME VARCHAR2(20),
PATIENT_AGE INT );

ALTER TABLE DEMO_1 ADD CONSTRAINT PATID_PK PRIMARY KEY (PATIENT_ID);

ALTER TABLE DEMO_1 ADD CONSTRAINT PATAGE_NN CHECK (PATIENT_AGE IS NOT NULL);

INSERT INTO DEMO_1 VALUES ('12345','XXXX',21);

INSERT INTO DEMO_1 VALUES ('&PATIENT_ID','&PATIENT_NAME',&PATIENT_AGE);

INSERT INTO DEMO_1 VALUES ('123','',21);

UPDATE  DEMO_1 SET PATIENT_NAME = 'RRRY' WHERE PATIENT_ID=123;

