SELECT *

FROM COUNTRIES C

INNER JOIN LOCATIONS L

ON C.COUNTRY_ID = L.COUNTRY_ID

WHERE L.STATE_PROVINCE IS NULL;

UPDATE LOCATIONS SET STATE_PROVINCE = 'XYZ' WHERE STATE_PROVINCE IS NULL;ROLLBACK;

