COMMIT
INSERT INTO EMPLOYEE_ID VALUES(1,'RAGAV','O+');

INSERT INTO EMPLOYEE_ID VALUES(2,'RANE','B+');

INSERT INTO EMPLOYEE_ID (EMP_ID,EMP_NAME,EMP_BLOODGRP) VALUES(3,'VIJE','A+');

INSERT INTO EMPLOYEE_ID VALUES (&EMP_ID,'&EMP_NAME','&EMP_BLOODGRP');

INSERT INTO EMPLOYEE_ID VALUES (&EMP_ID,'&EMP_NAME','&EMP_BLOODGRP');

INSERT INTO EMP_DEPT VALUES ('FABRIC',1,'OPERATOR','10000','KA',NULL);

INSERT INTO EMP_DEPT VALUES ('LOGISTIC',2,'OPERATOR','12000','KA',NULL);

INSERT INTO EMP_DEPT VALUES ('CUTTING',3,'SPREADER','13000','TN',NULL);

INSERT INTO EMP_DEPT VALUES ('SEWING',4,'FEEDING HELPER','10000','KA',NULL);

INSERT INTO EMP_DEPT VALUES ('SEWING',5,'SUPERVISOR','20000','KA',NULL);

COMMIT;


INSERT INTO ALL_TEST1 VALUES(2,'KOVAI','ENGLISH',TO_CHAR('12/JAN/2023'));




