SELECT I.EMP_ID,I.EMP_NAME,D.EMP_DESIGNATION,D.EMP_DEPARTMENT,D.EMP_SALARY--SPECIFIC COLUMNS AND * FOR WHOLE DATA OF RETRIVAL

FROM EMPLOYEE_ID I

INNER JOIN EMP_DEPT D --FULL OUTER JOIN,LEFT&RIGHT OUTER JOIN

ON D.EMP_ID=I.EMP_ID

WHERE ;

SELECT *

FROM REGIONS R

FULL OUTER JOIN COUNTRIES C


ON C.REGION_ID=R.REGION_ID

WHERE R.REGION_ID = 1 ;

SELECT *--EMP_ID,I.EMP_NAME,D.EMP_DESIGNATION,D.EMP_DEPARTMENT,D.EMP_SALARY--SPECIFIC COLUMNS AND * FOR WHOLE DATA OF RETRIVAL

FROM EMPLOYEE_ID 

JOIN EMP_DEPT  --FULL OUTER JOIN,LEFT&RIGHT OUTER JOIN

USING EMP_ID;



