SELECT COUNT(DEPARTMENT_ID) FROM DEPARTMENTS;--27

SELECT ROWNUM, EMPLOYEES.*
FROM EMPLOYEES 
WHERE SALARY > 10000;

SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE SALARY>10000;

SELECT EMPLOYEES.*
FROM EMPLOYEES
WHERE SALARY<10000 AND EMPLOYEE_ID > 115 AND MANAGER_ID > 150;




