SELECT * FROM EMPLOYEE_ID;

SELECT * FROM EMPLOYEE_ID WHERE EMP_ID =5;

SELECT * FROM COUNTRIES WHERE REGION_ID =1;

SELECT COUNT(*) FROM COUNTRIES WHERE REGION_ID =2;

SELECT * FROM JOB_HISTORY WHERE DEPARTMENT_ID=110;

SELECT * FROM EMP_DEPT WHERE EMP_ID IN (SELECT EMP_ID FROM EMPLOYEE_ID WHERE EMP_BLOODGRP ='A+');
