SELECT CONCAT ('RANJITH',' VANATHI') FROM DUAL;--RANJITH VANATHI

SELECT INITCAP ('ranjith vanathi') FROM DUAL;--Ranjith Vanathi

SELECT INSTR ('WAITED FOR ONE YEAR','O') FROM DUAL;--9

SELECT INSTR ('WAITED FOR ONE YEAR','O',10,1) FROM DUAL;--12

SELECT SUBSTR ('WAITED FOR ONE YEAR',1,19) FROM DUAL;--WAITED FOR ONE YEAR

SELECT SUBSTR('WAITED FOR ONE YEAR',1,4) FROM DUAL;--WAIT

SELECT SUBSTR('CHANGE NEVER CHANGE',-9,5) FROM DUAL;--ER CH

SELECT LENGTH('CHANGE NEVER CHANGE') FROM DUAL;--19

SELECT LENGTH('an account of past events in someones life or in the development of something') FROM DUAL;--77

SELECT INSTR ('an account of past events in someones life or in the development of something','in',28,1)FROM DUAL ;--47

SELECT UPPER ('an account of past events in someones life or in the development of something')FROM DUAL;--AN ACCOUNT OF PAST EVENTS IN SOMEONES LIFE OR IN THE DEVELOPMENT OF SOMETHING

SELECT LOWER ('AN ACCOUNT OF PAST EVENTS IN SOMEONES LIFE OR IN THE DEVELOPMENT OF SOMETHING')FROM DUAL; --an account of past events in someones life or in the development of something

SELECT TRIM ('      IDEAL') FROM DUAL;

SELECT TRIM (' ' FROM '   IDEAL') FROM DUAL;

SELECT TRIM ( LEADING '0' FROM 000123) FROM DUAL;--123

SELECT TRIM (TRAILING '3' FROM '000LEARN1233') FROM DUAL; --000LEARN12

SELECT TRIM (BOTH '0'FROM '0012LEARN3300') FROM DUAL;--12LEARN33
