SELECT E.FIRST_NAME||' '||LAST_NAME,E.EMAIL,E.JOB_ID,D.DEPARTMENT_NAME

FROM EMPLOYEES E

JOIN DEPARTMENTS D

ON E.DEPARTMENT_ID=D.DEPARTMENT_ID

WHERE PHONE_NUMBER=

(SELECT PHONE_NUMBER FROM EMPLOYEES WHERE EMPLOYEE_ID = 125);


SELECT *

FROM EMPLOYEES E

JOIN DEPARTMENTS D

ON E.DEPARTMENT_ID=D.DEPARTMENT_ID

JOIN JOB_HISTORY J

ON E.EMPLOYEE_ID=J.EMPLOYEE_ID

WHERE D.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM JOB_HISTORY WHERE JOB_ID IN ('IT_PROG' , 'AC_ACCOUNT'));


SELECT L.CITY, L.POSTAL_CODE ,COUNT(E.EMPLOYEE_ID)

FROM EMPLOYEES E

JOIN DEPARTMENTS D

ON E.DEPARTMENT_ID=D.DEPARTMENT_ID

JOIN LOCATIONS L

ON D.LOCATION_ID=L.LOCATION_ID

WHERE L.CITY IN 

(SELECT CITY FROM LOCATIONS)-- WHERE CITY IN ( 'Seattle' , 'Roma'))

GROUP BY L.CITY ,L.POSTAL_CODE

ORDER BY COUNT(E.EMPLOYEE_ID);


IF COUNT(E.EMPLOYEE_ID) <=10 THEN "UNDER THE BUDGET"

IF ELSE COUNT(E.EMPLOYEE_ID) > 10 THEN "OVER THE BUDGET"

ELSE "NULL"--UNDER QUERY





